[world]
name = "Wordle"
seed = "wordle"

[namespace]
default = "wordle"

[env]
rpc_url = "https://api.cartridge.gg/x/wordle-game/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"wordle" = ["wordle-actions"]

[lib_versions]
"wordle-word" = "0_0_1"

[init_call_args]
"wordle-actions" = ["0x0"]
