[package]
cairo = "=2.9.2"
name = "wordle"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
#cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf" }
#openzeppelin = "0.20.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
allowed-libfuncs-list.name = "experimental"

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
